// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// to_logical_
LogicalVector to_logical_(std::vector < std::string > x, std::vector < std::string > custom_true, std::vector < std::string > custom_false);
RcppExport SEXP batman_to_logical_(SEXP xSEXP, SEXP custom_trueSEXP, SEXP custom_falseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type custom_true(custom_trueSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type custom_false(custom_falseSEXP);
    __result = Rcpp::wrap(to_logical_(x, custom_true, custom_false));
    return __result;
END_RCPP
}
