// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// to_logical_
LogicalVector to_logical_(std::vector < std::string > x, std::vector < std::string > trues, std::vector < std::string > falses);
RcppExport SEXP batman_to_logical_(SEXP xSEXP, SEXP truesSEXP, SEXP falsesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type trues(truesSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type falses(falsesSEXP);
    __result = Rcpp::wrap(to_logical_(x, trues, falses));
    return __result;
END_RCPP
}
