# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

to_logical_ <- function(x, custom_true, custom_false) {
    .Call('batman_to_logical_', PACKAGE = 'batman', x, custom_true, custom_false)
}

